"""company branding fields (white-label)

Revision ID: 006fec3b2aa0
Revises: 931569fd10f9
Create Date: 2026-08-17 15:23:31.210747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006fec3b2aa0'
down_revision: Union[str, None] = '931569fd10f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=512), nullable=True))
    op.add_column('companies', sa.Column('favicon_url', sa.String(length=512), nullable=True))
    op.add_column('companies', sa.Column('primary_color', sa.String(length=7), nullable=True))
    op.add_column('companies', sa.Column('secondary_color', sa.String(length=7), nullable=True))
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_column('companies', 'secondary_color')
    op.drop_column('companies', 'primary_color')
    op.drop_column('companies', 'favicon_url')
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'domain')
    # ### end Alembic commands ###