"""billing asaas: billing_charges + company billing fields

Revision ID: 06ef9ea19356
Revises: 936c34583960
Create Date: 2026-09-17 16:25:35.992911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ef9ea19356'
down_revision: Union[str, None] = '936c34583960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###