"""add purchase rules to companies

Revision ID: 27772ef2a0b6
Revises: 06ef9ea19356
Create Date: 2026-09-18 14:39:10.180631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27772ef2a0b6'
down_revision: Union[str, None] = '06ef9ea19356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('min_order_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('companies', sa.Column('min_order_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'min_order_quantity')
    op.drop_column('companies', 'min_order_value')
    # ### end Alembic commands ###