"""add chat_sector to users

Revision ID: 345e6bf2b40c
Revises: 9f8f5d959946
Create Date: 2026-09-08 17:00:27.162522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345e6bf2b40c'
down_revision: Union[str, None] = '9f8f5d959946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_sector', sa.Enum('sales', 'commercial', 'financial', 'support', 'service', name='chat_sector'), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_sector')
    # ### end Alembic commands ###