"""add mfa recovery codes to users

Revision ID: 46a4f2e4f1ce
Revises: 72a43d71fe7b
Create Date: 2026-09-13 17:44:46.133597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a4f2e4f1ce'
down_revision: Union[str, None] = '72a43d71fe7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###