"""add mfa recovery codes to users

Revision ID: 72a43d71fe7b
Revises: c15a2db587c6
Create Date: 2026-09-13 17:16:26.665531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72a43d71fe7b'
down_revision: Union[str, None] = 'c15a2db587c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_recovery_codes_hashed', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_recovery_codes_hashed')
    # ### end Alembic commands ###