"""billing asaas: billing_charges + company billing fields

Revision ID: 73e87bce61f3
Revises: 46a4f2e4f1ce
Create Date: 2026-09-17 15:46:43.214136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e87bce61f3'
down_revision: Union[str, None] = '46a4f2e4f1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_charges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('billing_type', sa.Enum('pix', 'boleto', 'credit_card', name='billing_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'overdue', 'cancelled', 'refunded', name='billing_status'), server_default='pending', nullable=False),
    sa.Column('asaas_payment_id', sa.String(length=100), nullable=True),
    sa.Column('asaas_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('checkout_url', sa.String(length=512), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_billing_charges_tenant_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_charges'))
    )
    op.create_index(op.f('ix_billing_charges_asaas_payment_id'), 'billing_charges', ['asaas_payment_id'], unique=False)
    op.create_index(op.f('ix_billing_charges_asaas_subscription_id'), 'billing_charges', ['asaas_subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_charges_external_reference'), 'billing_charges', ['external_reference'], unique=False)
    op.create_index(op.f('ix_billing_charges_tenant_id'), 'billing_charges', ['tenant_id'], unique=False)
    op.create_index('ix_billing_charges_tenant_status', 'billing_charges', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_billing_charges_tenant_type', 'billing_charges', ['tenant_id', 'type'], unique=False)
    op.add_column('companies', sa.Column('asaas_customer_id', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('monthly_fee', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_companies_asaas_customer_id'), 'companies', ['asaas_customer_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_asaas_customer_id'), table_name='companies')
    op.drop_column('companies', 'monthly_fee')
    op.drop_column('companies', 'asaas_customer_id')
    op.drop_index('ix_billing_charges_tenant_type', table_name='billing_charges')
    op.drop_index('ix_billing_charges_tenant_status', table_name='billing_charges')
    op.drop_index(op.f('ix_billing_charges_tenant_id'), table_name='billing_charges')
    op.drop_index(op.f('ix_billing_charges_external_reference'), table_name='billing_charges')
    op.drop_index(op.f('ix_billing_charges_asaas_subscription_id'), table_name='billing_charges')
    op.drop_index(op.f('ix_billing_charges_asaas_payment_id'), table_name='billing_charges')
    op.drop_table('billing_charges')
    # ### end Alembic commands ###