"""cria tabela quantity_discounts (desconto por quantidade)

Revision ID: 92c78257575e
Revises: f9063623ad10
Create Date: 2026-09-10 12:05:28.320187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c78257575e'
down_revision: Union[str, None] = 'f9063623ad10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantity_discounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.Enum('percent', 'fixed', name='discount_type'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_quantity_discounts_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_quantity_discounts_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_quantity_discounts_tenant_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quantity_discounts'))
    )
    op.create_index('ix_qty_discounts_product', 'quantity_discounts', ['tenant_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_quantity_discounts_customer_id'), 'quantity_discounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quantity_discounts_product_id'), 'quantity_discounts', ['product_id'], unique=False)
    op.create_index(op.f('ix_quantity_discounts_tenant_id'), 'quantity_discounts', ['tenant_id'], unique=False)
    op.create_index('uq_qty_discounts_customer', 'quantity_discounts', ['tenant_id', 'product_id', 'customer_id', 'min_quantity'], unique=True, postgresql_where=sa.text('customer_id IS NOT NULL'))
    op.create_index('uq_qty_discounts_global', 'quantity_discounts', ['tenant_id', 'product_id', 'min_quantity'], unique=True, postgresql_where=sa.text('customer_id IS NULL'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_qty_discounts_global', table_name='quantity_discounts', postgresql_where=sa.text('customer_id IS NULL'))
    op.drop_index('uq_qty_discounts_customer', table_name='quantity_discounts', postgresql_where=sa.text('customer_id IS NOT NULL'))
    op.drop_index(op.f('ix_quantity_discounts_tenant_id'), table_name='quantity_discounts')
    op.drop_index(op.f('ix_quantity_discounts_product_id'), table_name='quantity_discounts')
    op.drop_index(op.f('ix_quantity_discounts_customer_id'), table_name='quantity_discounts')
    op.drop_index('ix_qty_discounts_product', table_name='quantity_discounts')
    op.drop_table('quantity_discounts')
    # ### end Alembic commands ###