"""bloco14_indices_performance

Revision ID: 931569fd10f9
Revises: caffea54e7cc
Create Date: 2026-08-14 17:49:37.819051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931569fd10f9'
down_revision: Union[str, None] = 'caffea54e7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_ticket_status_history_tenant_id_companies'), 'ticket_status_history', 'companies', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ticket_status_history_tenant_id_companies'), 'ticket_status_history', type_='foreignkey')
    # ### end Alembic commands ###