"""billing asaas: billing_charges + company billing fields

Revision ID: 936c34583960
Revises: a8dfc921fef8
Create Date: 2026-09-17 16:07:13.950485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936c34583960'
down_revision: Union[str, None] = 'a8dfc921fef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###