"""billing asaas: billing_charges + company billing fields

Revision ID: a8dfc921fef8
Revises: 73e87bce61f3
Create Date: 2026-09-17 15:56:29.011723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8dfc921fef8'
down_revision: Union[str, None] = '73e87bce61f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###