"""cart order user customer link

Revision ID: ae6a775378af
Revises: f29ab5aebcfc
Create Date: 2026-08-14 02:56:20.934862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6a775378af'
down_revision: Union[str, None] = 'f29ab5aebcfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_customer_id'), 'users', ['customer_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_customer_id_customers'), 'users', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_customer_id_customers'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_customer_id'), table_name='users')
    op.drop_column('users', 'customer_id')
    # ### end Alembic commands ###