"""add customer_id to invitations

Revision ID: d44b92f6077b
Revises: 55bb27e08a49
Create Date: 2026-08-27 20:58:22.727198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44b92f6077b'
down_revision: Union[str, None] = '55bb27e08a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invitations_customer_id'), 'invitations', ['customer_id'], unique=False)
    op.create_foreign_key(op.f('fk_invitations_customer_id_customers'), 'invitations', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invitations_customer_id_customers'), 'invitations', type_='foreignkey')
    op.drop_index(op.f('ix_invitations_customer_id'), table_name='invitations')
    op.drop_column('invitations', 'customer_id')
    # ### end Alembic commands ###