"""torna estoque inteiro (Integer) e schema/cache int

Revision ID: f9063623ad10
Revises: 345e6bf2b40c
Create Date: 2026-09-09 23:01:36.913247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9063623ad10'
down_revision: Union[str, None] = '345e6bf2b40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'stock',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'stock',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###